version: 2.1
orbs:
  react: thefrontside/react@0.2.0
jobs:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/stylelint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
workflows:
  sample:
    jobs:
      - push
